model_selection:
    model:
      GaussianNB:
        search_param_grid:
          var_smoothing:
            - 0.5
            - 0.05
            - 0.01

      XGBClassifier:
        search_param_grid:
          max_depth: 
           - 3
           - 5
           - 7
           - 9
           - 11
          n_estimators:
           - 50
           - 100
           - 130
          random_state:
            - 0
            - 50
            - 100
      SVC:
        search_param_grid:
          C:
            - 1.0
            - 10.0
            - 100.0
          kernel:
            - 'linear'
            - 'poly'
            - 'rbf'
          gamma:
            - 'scale'
            - 'auto'
          random_state:
            - 0
            - 42
            - 100

      RandomForestClassifier:
        search_param_grid:
          n_estimators:
            - 100
            - 200
            - 300
          max_depth:
            - 10
            - 20
            - 30
          min_samples_split:
            - 2
            - 5
            - 10
          random_state:
            - 0
            - 42
            - 100

      GradientBoostingClassifier:
        search_param_grid:
          learning_rate:
            - 0.01
            - 0.1
            - 0.2
          n_estimators:
            - 100
            - 200
            - 300
          max_depth:
            - 3
            - 5
            - 9
          random_state:
            - 0
            - 42
            - 100

          
      
